Section/header
whiteblackswan/agency pull request #2
Opened 2023-04-04 17:33 UTC by whiteblackswan

2023-04-04 18:17 UTC, Dmitruk89 requested changes

2023-04-07 10:01 UTC, whiteblackswan commented on sass/_general.sass
> +.nav-links li a:hover
I fixed everything

2023-04-07 10:02 UTC, whiteblackswan commented on sass/_home.sass
> +			background-color: yellow
I fixed everything

2023-04-07 10:03 UTC, whiteblackswan commented on js/script.js
> +const navLinks = document.getElementsByClassName('nav-links')[0]
I fixed everything

2023-04-07 10:03 UTC, whiteblackswan commented on js/script.js
> +menuButton.forEach(n => n.addEventListener("click", closeMenu));
I fixed everything

2023-04-07 10:03 UTC, whiteblackswan commented on js/script.js
> +}
I fixed everything

2023-04-07 10:22 UTC, whiteblackswan commented on sass/_general.sass
> +	font-size: 16px
I fixed everything

2023-04-09 19:23 UTC, Dmitruk89 approved these changes

2023-04-11 09:34 UTC, merged