Section/home
whiteblackswan/agency pull request #3
Opened 2023-04-11 10:04 UTC by whiteblackswan

Demo: https://gorgeous-centaur-020a49.netlify.app/
Add section home with title and adaptive responsive design.

2023-04-11 13:36 UTC, Dmitruk89 commented
![image](https://user-images.githubusercontent.com/57582285/231179894-0b5dc8d7-f948-4f36-8924-bb52c7447ad4.png)
just proposal: you have no yellow color in your design template, so better to change hover style for this button, e. g. simply reduce the opacity a little bit.

2023-04-11 13:55 UTC, Dmitruk89 requested changes

2023-04-11 13:55 UTC, Dmitruk89 commented on sass/_general.sass
> +			padding-top: 1px
does the 1px padding really make sence?

2023-04-11 13:55 UTC, Dmitruk89 commented on sass/_home.sass
> +	background: $main-green
create a class for that properties, It will be useful for the second similar section.

2023-04-11 13:55 UTC, Dmitruk89 commented on sass/_home.sass
> +		margin: 0 auto
try adding text-align: center for the section here instead of positioning all the elements individually

2023-04-11 13:55 UTC, Dmitruk89 commented on index.html
> +				<div class="button__wrap">
why do you need wrapper for the button here? check, maybe you can remove it

2023-04-11 13:55 UTC, Dmitruk89 commented on index.html
> +					<button class="button button__main">
button__main - is not good for this button, better use section-home__button

2023-04-11 13:55 UTC, Dmitruk89 commented on sass/_home.sass
> +		align-items: center
I think it is possible to remove this wrapper, just add some properties directly to the button, in case losing it's positioning;

2023-04-12 07:06 UTC, whiteblackswan commented on sass/_general.sass
> +			padding-top: 1px
I agree with what you say. but this is make sense for the line.

2023-04-12 08:43 UTC, whiteblackswan commented on sass/_home.sass
> +	margin: 0 auto
I add a new file to Sass for reuse later.
![jtYB490dwo](https://user-images.githubusercontent.com/111532122/231402978-3d9a733e-eca7-4582-9fe5-b99d1cc2acb1.png)
![dHx9uR374v](https://user-images.githubusercontent.com/111532122/231402985-e4346520-4239-45af-b942-3db0c503d179.png)

2023-04-12 08:47 UTC, whiteblackswan commented on sass/_home.sass
> +		margin: 0 auto
I fixed it.

2023-04-12 08:52 UTC, whiteblackswan commented on index.html
> +		<section class="section-home section-home--green">
corrected the name according to bem

2023-04-12 11:56 UTC, whiteblackswan commented on index.html
> +				<div class="button__wrap">
I left this wrapper, because it is better to arrange the elements.

2023-04-12 12:00 UTC, whiteblackswan commented on sass/_home.sass
> +		align-items: center
I left this wrapper.

2023-04-13 10:59 UTC, Dmitruk89 approved these changes

2023-04-13 12:09 UTC, merged