Section/icons
whiteblackswan/agency pull request #5
Opened 2023-04-14 10:05 UTC by whiteblackswan

This is link to netlify.

https://tranquil-sorbet-a8923c.netlify.app/

2023-04-15 16:02 UTC, Dmitruk89 commented
![image](https://user-images.githubusercontent.com/57582285/232235747-2124add3-f350-491a-bac6-855756d82b25.png)
Please reduce the height of sections on smaller screens, mainly to avoid the green section appeared in bottom of slider.

2023-04-15 16:06 UTC, Dmitruk89 commented
![image](https://user-images.githubusercontent.com/57582285/232236073-521b569e-fec8-4fd5-9623-1b7cc32356cf.png)
on the breakpoint about 910px, the height of the slides start jumping causing overlap with the elements on the buttom

2023-04-15 16:39 UTC, Dmitruk89 requested changes

2023-04-15 16:39 UTC, Dmitruk89 commented on index.html
> +			<div class="container">
this is slider container, so please change the name to "slider__container"

2023-04-15 16:39 UTC, Dmitruk89 commented on index.html
> +				<div class="slide-container">
according to the BEM, name this class as slide__container

2023-04-15 16:39 UTC, Dmitruk89 commented on index.html
> +				<div class="dots-container">
the same here: "dots__container" or better "dot-list"

2023-04-15 16:39 UTC, Dmitruk89 commented on index.html
> +			<div class="container">
if this container common for all the section, you may call it "section__container"

2023-04-15 16:39 UTC, Dmitruk89 commented on index.html
> +		<section class="icons">
you may call this block "statistic" then rename the classes "flex-container" and "flex-block" according to the BEM

2023-04-15 16:39 UTC, Dmitruk89 commented on js/script.js
> +var currentSlide = 0;
use "let" here

2023-04-15 16:39 UTC, Dmitruk89 commented on sass/_slider.sass
> +	margin-right: auto
this two properties gives no effect, you may clear them

2023-04-15 16:39 UTC, Dmitruk89 commented on sass/_slider.sass
> +	margin-top: -250px
giving negative margin is bad practice. Try find another solution (e.g. using "top" with negative values is ok)

2023-04-15 16:39 UTC, Dmitruk89 commented on sass/_slider.sass
> +
remove this empty line

2023-04-15 16:39 UTC, Dmitruk89 commented on sass/_slider.sass
> +	margin-top: -22px
the same negative margin, please replace it with something else

2023-04-15 16:39 UTC, Dmitruk89 commented on sass/_slider.sass
> +	color: white
I guess you use constants for colors

2023-04-15 16:39 UTC, Dmitruk89 commented on sass/_slider.sass
> +	color: #333
please use constants for colors

2023-04-15 17:42 UTC, whiteblackswan commented on index.html
> +			<div class="container">
You're right, that's make sense.

2023-04-16 05:35 UTC, whiteblackswan commented on index.html
> +			<div class="container">
I checked this, and on line 63, I have a container that holds the entire width.

2023-04-16 05:35 UTC, whiteblackswan commented on index.html
> +				<div class="slide-container">
This makes sense, I fixed it.

2023-04-16 06:35 UTC, whiteblackswan commented on index.html
> +			<div class="container">
I fixed it.

2023-04-16 06:36 UTC, whiteblackswan commented on index.html
> +		<section class="icons">
I fixed it

2023-04-16 06:38 UTC, whiteblackswan commented on sass/_slider.sass
> +
I fixed it.

2023-04-16 06:39 UTC, whiteblackswan commented on sass/_slider.sass
> +	color: white
I fixed it.

2023-04-16 06:41 UTC, whiteblackswan commented on sass/_slider.sass
> +	color: #333
I fixed it.

2023-04-17 15:38 UTC, whiteblackswan commented on sass/_slider.sass
> +	margin-top: -250px
I fixed it

2023-04-17 15:38 UTC, whiteblackswan commented on sass/_slider.sass
> +	margin-top: -22px
I fixed it.

2023-04-17 15:44 UTC, Dmitruk89 commented on index.html
> +					</div>
it is more proper to use name "statistic__item" as statistic block - it is section "statistic". other mentions of block causes some confusions.

2023-04-17 16:00 UTC, whiteblackswan commented on index.html
> +					</div>
You are right, I didn't notice.

2023-04-17 16:03 UTC, whiteblackswan commented on js/script.js
> +var currentSlide = 0;
I fixed it

2023-04-17 16:41 UTC, Dmitruk89 approved these changes

2023-04-17 17:10 UTC, merged